# Generated by Django 5.2.4 on 2026-03-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspaper',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='newspapers/'),
        ),
    ]
