# Generated by Django 5.2.4 on 2026-03-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0003_supportticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to='support/'),
        ),
    ]
