# Generated by Codex on 2026-03-12

from django.db import migrations, models


def migrate_newspaper_statuses(apps, schema_editor):
    Newspaper = apps.get_model('newsroom', 'Newspaper')
    Newspaper.objects.filter(status__in=['draft', 'review']).update(status='published')


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0004_supportticket_attachment'),
    ]

    operations = [
        migrations.RunPython(migrate_newspaper_statuses, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='newspaper',
            name='status',
            field=models.CharField(
                choices=[('published', 'Опубликована')],
                default='published',
                max_length=20,
            ),
        ),
    ]
