# Generated by Codex on 2026-03-12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0005_alter_newspaper_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspaper',
            name='issue_number',
        ),
    ]
